image: docker:stable

services:
  - docker:dind

before_script:
  - apk add --no-cache py-pip
  - pip install docker-compose
  - docker info
  - docker-compose --version
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN lab.wienerdeming.com:4567
  - id -un

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker build -t lab.wienerdeming.com:4567/gs1/gs1_ui .
    - docker push lab.wienerdeming.com:4567/gs1/gs1_ui
  tags:
    - staging

test:
  stage: test
  script:
    - docker-compose run test
  tags:
    - staging

deploy:
  stage: deploy
  script:
    - docker-compose run app
    - cp -r dist/ /gs1_ui
  only:
    - master
  tags:
    - staging

