image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_REGISTRY: lab.wienerdeming.com:4567
  CONTAINER_RELEASE_IMAGE: lab.wienerdeming.com:4567/gs1/gs1_ui

before_script:
  - apk add --no-cache py-pip
  - pip install docker-compose
  - docker info
  - docker-compose --version
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY
  - id -un

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker build -t $CONTAINER_RELEASE_IMAGE .
    - docker push $CONTAINER_RELEASE_IMAGE
  tags:
    - staging

test:
  stage: test
  script:
    - docker pull $CONTAINER_RELEASE_IMAGE
    - docker-compose run test
  tags:
    - staging

deploy:
  stage: deploy
  script:
    - docker pull $CONTAINER_RELEASE_IMAGE
    - docker-compose run app
  only:
    - master
  tags:
    - staging
