version: "3"

services:
  test:
    environment:
      - NODE_ENV=testing
    build: .
    image: lab.wienerdeming.com:4567/gs1/gs1_ui

  app:
    environment:
      - NODE_ENV=production
      - API_HOST=apigs1.wienerdeming.com
    build: .
    image: lab.wienerdeming.com:4567/gs1/gs1_ui
    volumes:
      - "/var/www/gs1_ui/dist:/var/www/gs1_ui/dist"
