version: "3"

services:
  # App
  test:
    environment:
      - NODE_ENV=testing
    build: .

  app:
    env_file:
      - .env
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./dist:/gs1_ui

